### ISSUE TITLE
Nanites Ignore Role based settings

### ISSUE THREAD

**Issue by JamieKG** [Nanite-Construction-System/NaniteConstructionSystem#102]
Looks like nanites ignore all role based settings 
https://i.imgur.com/belveEg.png

**Comment by nukeguard** [comment]
do they still construct or deconstruct whilst those are unchecked?

**Comment by CommanderDoenner** [comment]
> 
> 
> do they still construct or deconstruct whilst those are unchecked?

Yes they do. even destructig the factorys could not stop the nanites from deconstructing my beautiful rover. It seems that the algorythm checking if the beacon, or the checkmark is still there not recognizing changes during deconstruction.

**Comment by f4ble** [comment]
> 
> 
> do they still construct or deconstruct whilst those are unchecked?

I can confirm. I have a mining-only Nanite Factory that ignores setting and does building. No beacons even remotely nearby.
