### ISSUE TITLE
After a while all game processes stop (re-colouring, nanite construction) and then freezes on quit

### ISSUE THREAD

**Issue by Phteven98** [Nanite-Construction-System/NaniteConstructionSystem#113]
After a few minutes in game the in-game processes such as those in title stop completely. When attempting to quit to main menu the game "freezes" on the pause menu. The blue space engineers cursor still moves as normal but nothing else works, meaning the game needs killing through the task manager.

**Comment by Zemogiter** [comment]
This affects me as well but I've got nothing in either log files.

**Comment by nukeguard** [comment]
I have someone on my discord that will be taking a look at the scripting in nanites, hopefully we can get the issues addressed.

**Comment by Se-Zarkash** [comment]
I`m having almost the same problem, but I can play for a long time before things eventually freezes, showing the grinding issues Zemogiter wrote about.
But no matter how long I play, the game will freeze when trying to exit to menu.

Quick summary:
In NaniteConstructionSystem.log there is only one index out of bounds error, as far as I could see.
In SpaceEngineers.log it looks like its reporting errors for beacon.

Here are the log files:
[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/3986312/NaniteConstructionSystem.log)
[SpaceEngineers.log](https://github.com/nukeguard/NaniteConstructionSystem/files/3986315/SpaceEngineers.log)

**Comment by Zemogiter** [comment]
After some time I've encountered this issue again.
[SpaceEngineers.log](https://github.com/nukeguard/NaniteConstructionSystem/files/4005813/SpaceEngineers.log)
[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/4005819/NaniteConstructionSystem.log)
I don't see any error in that log though.
[Sandboxed Exploration.zip](https://github.com/nukeguard/NaniteConstructionSystem/files/4005817/Sandboxed.Exploration.zip)

**Comment by nukeguard** [comment]
This is a bug still occuring, has been confirmed

**Comment by M0dEx** [comment]
I managed to reproduce it with the Nanite Ore Detector only. Have you experienced the issue without it? @Se-Zarkash @Zemogiter @Phteven98

**Comment by Phteven98** [comment]
I havent played any more single player with it I'm afraid, I'll have a try
and see if I can replicate it again when I'm back from work

**Comment by Zemogiter** [comment]
@M0dEx The issue was present before Nanite Ore Detector was present in the save.

**Comment by M0dEx** [comment]
@Zemogiter Does the issue still happen?

**Comment by MarioPL98** [comment]
The issue is still there. Had that issue few times in last couple of hours.

**Comment by M0dEx** [comment]
@Phteven98 Could you kindly go to the mod config and change the value of DebugLevel to 1, try to replicate the issue and send me the log? Thanks.

**Comment by Phteven98** [comment]
Will do, but its 2 am here and I'm going to bed, so please remind me in 12
hours then yes I will

**Comment by Zemogiter** [comment]
@M0dEx the issue is still present. Quiting to main menu hangs the game.
[SpaceEngineers_20200508_12224241.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4598612/SpaceEngineers_20200508_12224241.log)
[VRageRender-DirectX11_20200508_122247417.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4598616/VRageRender-DirectX11_20200508_122247417.log)
[NaniteConstructionSystem.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4598624/NaniteConstructionSystem.log)
[Sandboxed Exploration.zip](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4598630/Sandboxed.Exploration.zip)
DebugLog is set to 1

**Comment by M0dEx** [comment]
@Zemogiter 

The only suspicious thing I found in the logs is this:
`2020-05-08 13:11:33.866 - Thread:  24 ->  TryChangeToFullscreen failed with HRESULT = 0x887A0022`

And it seems this error was causing hang ups for some people as well -> [link](https://www.reddit.com/r/spaceengineers/comments/fzcm1u/space_engineers_is_not_responding/)

You can try the solution mentioned in the thread, but I am not very optimistic, since this bug presents only while having NCS installed (could you confirm this?). I'll try to take a look at the world and play around for a bit to see, if I can replicate it myself.

**Comment by Zemogiter** [comment]
@M0dEx tried it, didn't help

**Comment by M0dEx** [comment]
> @M0dEx tried it, didn't help

@Zemogiter 

I couldn't replicate the bug with your save, how do you trigger it?

**Comment by Zemogiter** [comment]
@M0dEx just by quiting to menu, then confirming on save popup when nanite controll was deconstricting a grid.

**Comment by Phteven98** [comment]
It will happen only if in game processes stop, so place down a large number
of unbuilt blocks and wait until the nanites stop working, you will see you
can't paint anything and at that point try to exit the game to the menu, it
will freeze forcing a task manager shutdown

**Comment by Martmists-GH** [comment]
Similar issue on a server; Mod works fine until something is deconstructed, causing a crash after a little while (been unable to locate where logs are stored so far)

**Comment by Martmists-GH** [comment]
My issue seems unrelated to NCS, breaking some of these blocks manually also forces a server restart. Does anyone know how to get server logging to be more verbose so I can track down the issue?

**Comment by Zemogiter** [comment]
This bug happend to me again. Upon pressing "quit to main menu" and confirming saving the game hanged, hiting alt+F4 results in the game's window's closure but the game's process remains. Had to shutdown Steam to make it visible in task manager (I haven't tried taskkill). Will once again try with a new world with only this mod active.

[NaniteConstructionSystem.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4875680/NaniteConstructionSystem.log)
[SpaceEngineers_20200705_215509114.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4875663/SpaceEngineers_20200705_215509114.log)
http://www.mediafire.com/file/wjclgkjd4i9pfqv/New_Exploration.zip

UPDATE: I've managed to recreate the issue on a new save with just this mod loaded.
[NaniteConstructionSystem.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4881170/NaniteConstructionSystem.log)
[SpaceEngineers_20200706_21495159.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4881162/SpaceEngineers_20200706_21495159.log)
[Earth Planet 2020-07-05 23-30.zip](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4881167/Earth.Planet.2020-07-05.23-30.zip)

@nukeguard please take a look

**Comment by nukeguard** [comment]
issue fixed
