### ISSUE TITLE
target selection is weird?

### ISSUE THREAD

**Issue by imperialR3D** [Nanite-Construction-System/NaniteConstructionSystem#116]
I'm using this mod for the first time because I want to make an automated factory but I've run into some problems. I cant get the control facility to select a target. now, for all I know I could be doing something wrong but what brought me here was the fact that when I checked the facility all nanite categories (including the projection nanites I was trying to set up) were showing no possible targets except for the cleanup nanites in which the possible targets were multiplying by nines (9, 18, 27, etc...). even after I had used one of the Nanite projection construction beacons, the facility didn't  read a possible target under the projection nanites' category. I also wanted to know what targets it was reading under cleanup so I enabled the cleanup function and the facility still refused to select a target. oddly enough, when I first build the facility it turns blue and starts constructing a nanite almost the second I enable it, however the nanite just stands there for a while with all those effects around it then disappears

update: I got the nanites to deconstruct a grid and pick up lost ore, still don't know about projections, or why its reading so many non-existent cleanup tasks. 
 
update 2: now that I have a deconstruction beacon in place the facility will only select deconstruction targets, even though I have a projection beacon that is much closer and the deconstruct option is still unchecked

update 2.1: despite the fact that the facility has the deconstruction target selected (against me telling it not to deconstruct), it doesn't appear to be sending any streams of nanites to actually deconstruct the grid (still deconstructs if i check the box though). this also only appears to happen when another facility is targeting something for deconstruction, otherwise it just doesn't select a target or read the other beacons.

update 3: okay, so turns out I'm an idiot who doesn't know how to use holograms and freaked out about a bug before going through all of the steps (I just had the hologram positioned wrong).

**Comment by nukeguard** [comment]
there are a couple ppl looking at updating and fixing bugs, so hopefully in the near future some of this will get cleared up.
