### ISSUE TITLE
Current "InvalidTarget" issue 06May20

### ISSUE THREAD

**Issue by RyukoJohn** [Nanite-Construction-System/NaniteConstructionSystem#120]
Attached data is is for current identified issue of "InvalidTarget" as discussed in steam forums.  Please see the video at https://youtu.be/MOggYRj6aDI which corresponds to all logs.  (I turned off space engineers; relaunched, started recording, performed video, and then turned off space engineers, then turned off recording so video closely tied to debug reports).

In short, nanites start doing their thing, but seem to crash after the first cycle.  Currently nanite factory is the only mod on server, scene is fairly complex as it is a center hub for everyone that plays, nanites are set to repair, build projects, and deconstruct (I had issues last week where the game would stop saving and i had to redownload the mod that seemed to go away when I removed my 2nd facility and turned off cleanup).  It is an online, non-server mode game.

[SpaceEngineersNaniteFactoryFullReport.zip](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4592983/SpaceEngineersNaniteFactoryFullReport.zip)

**Comment by M0dEx** [comment]
@RyukoJohn

Should be fixed with #122.

Please try to recreate the issue after the next fix is released and let me know!

**Comment by M0dEx** [comment]
@RyukoJohn

Fixed with #128.

**Comment by SvenBrnn** [comment]
I've also got a similar problem.
We are only using the nanites for construction + cleanup. SInce yesterday (or maybe 2 days before since we didn't have time playing) the construction stopped working.
Nanites are always complaining that the maximum number of construction targets are already reached with 3 construction upgrades + no nanites in use.

We are using some mods on the server, most are new blocks. An extended range ore detector (which should not matter with mining not in use) and an teleporter mod.

```
`[14:19:48] Loading: FactoryTerminalSettings.dat
[14:19:48] Loading: AssemblerTerminalSettings.dat
[14:19:48] Loading: BeaconTerminalSettings.dat
[14:19:50] Loading Settings
[14:19:50] IsClient: False | IsServer True | IsDedicated True
[14:19:50] Logging Started: Nanite Control Facility | Version 2.0 | Build 6
```

**Comment by SvenBrnn** [comment]
UPDATE:
i've just edited the config and set the scanned blocks per second to 500 manually (it did not update for me). After increesing the power a bit more it seems to be working again (seems like 2 batteries were not enough for them ^^)

**Comment by RyukoJohn** [comment]
All appears to be working now
