### ISSUE TITLE
Change Medical Nanites to Life Support Nanites

### ISSUE THREAD

**Issue by M0dEx** [Nanite-Construction-System/NaniteConstructionSystem#129]
Make Medical Nanites replenish oxygen and hydrogen too.

**Comment by M0dEx** [comment]
The Life Support nanites currently replenish health, oxygen, hydrogen and power.

With the latest commit (393e765), the mod checks if there is oxygen and hydrogen available and if there's not, it doesn't replenish them. However, I couldn't find an effective nor safe way to remove gases from tanks, so it is basically a free refill. For late game players (which is usually when the NCF is built), this is not much of an issue, since they probably have tons of gases anyway.

**Comment by GuillaumeHemmen** [comment]
> The Life Support nanites currently replenish health, oxygen, hydrogen and power.
> 
> With the latest commit ([393e765](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/commit/393e76538ebaf778258709535081d616bcfb0e7a)), the mod checks if there is oxygen and hydrogen available and if there's not, it doesn't replenish them. However, I couldn't find an effective nor safe way to remove gases from tanks, so it is basically a free refill. For late game players (which is usually when the NCF is built), this is not much of an issue, since they probably have tons of gases anyway.

Can the oxygen and hydrogen feature be a configurable feature?

**Comment by M0dEx** [comment]
> > The Life Support nanites currently replenish health, oxygen, hydrogen and power.
> > With the latest commit ([393e765](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/commit/393e76538ebaf778258709535081d616bcfb0e7a)), the mod checks if there is oxygen and hydrogen available and if there's not, it doesn't replenish them. However, I couldn't find an effective nor safe way to remove gases from tanks, so it is basically a free refill. For late game players (which is usually when the NCF is built), this is not much of an issue, since they probably have tons of gases anyway.
> 
> Can the oxygen and hydrogen feature be a configurable feature?

If you change the values of refill levels for oxygen and hydrogen to 0, they will never get refilled. Same goes for power, too.

**Comment by GuillaumeHemmen** [comment]
> > > The Life Support nanites currently replenish health, oxygen, hydrogen and power.
> > > With the latest commit ([393e765](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/commit/393e76538ebaf778258709535081d616bcfb0e7a)), the mod checks if there is oxygen and hydrogen available and if there's not, it doesn't replenish them. However, I couldn't find an effective nor safe way to remove gases from tanks, so it is basically a free refill. For late game players (which is usually when the NCF is built), this is not much of an issue, since they probably have tons of gases anyway.
> > 
> > 
> > Can the oxygen and hydrogen feature be a configurable feature?
> 
> If you change the values of refill levels for oxygen and hydrogen to 0, they will never get refilled. Same goes for power, too.

That's perfect, thanks a million.
