### ISSUE TITLE
Latest Version broke saves

### ISSUE THREAD

**Issue by dtgnoome** [Nanite-Construction-System/NaniteConstructionSystem#130]
That. as a note no blocks have been built inside the world the save just wont load.

These are the three latest log files. 

[SpaceEngineers_20200509_115614756.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4604204/SpaceEngineers_20200509_115614756.log)
[SpaceEngineers_20200509_131615442.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4604205/SpaceEngineers_20200509_131615442.log)
[SpaceEngineers_20200509_13250016.log](https://github.com/Nanite-Construction-System/NaniteConstructionSystem/files/4604206/SpaceEngineers_20200509_13250016.log)

**Comment by seulil** [comment]
aye same here

**Comment by RavenXIII** [comment]
Same here

2020-05-10 03:44:52.423 - Thread:   1 ->     No definition 'MyObjectBuilder_UpgradeModule/NaniteMedicalUpgrade'. Maybe a mistake in XML?

Edit: Manually reverted the changes to A2_nanite_CubeBlocks.sbc and game loads fine

**Comment by nukeguard** [comment]
block crash is fixed
