### ISSUE TITLE
Nanites trying to build projection even though projection construction is off.

### ISSUE THREAD

**Issue by pixelblob** [Nanite-Construction-System/NaniteConstructionSystem#131]
The nanites arent building the projectection just floating around it, its causing me to loose all my power because it keeps sending nanites.

**Comment by M0dEx** [comment]
Hi @pixelblob,

I'll need you to do the following:

1. Go to %AppData%\SpaceEngineers\Saves\\<steam_id>\\<world_name>\Storage\219757726.sbm_NaniteConstructionSystem, open Config.xml and change `<DebugLogging>0</DebugLogging>` to `<DebugLogging>1</DebugLogging>`
2. Load the save in the game and replicate the issue.
3. Post NaniteConstructionSystem.log, SpaceEngineers\_\<date\>.log and the save as a reply to this issue.

Thanks!
