### ISSUE TITLE
Graphic bug while building

### ISSUE THREAD

**Issue by Elias11022** [Nanite-Construction-System/NaniteConstructionSystem#150]
Hello great MOD!!
I have some bugs the importens bug is ... if I deconstruct a block (manual) the block is visible for 30min - 1h. the same is I build a Block with nanites the block is build but nothing is visible for a long time.

**Comment by M0dEx** [comment]
Hi @Elias11022,

I'll need you to do the following:

1. Go to %AppData%\SpaceEngineers\Saves\\<steam_id>\\<world_name>\Storage\219757726.sbm_NaniteConstructionSystem, open Config.xml and change `<DebugLogging>0</DebugLogging>` to `<DebugLogging>1</DebugLogging>`
2. Load the save in the game and replicate the issue.
3. Post NaniteConstructionSystem.log, SpaceEngineers\_\<date\>.log and the save as a reply to this issue.

Thanks!

**Comment by Elias11022** [comment]
> Hi @Elias11022,
> 
> I'll need you to do the following:
> 
> 1. Go to %AppData%\SpaceEngineers\Saves\<steam_id>\<world_name>\Storage\219757726.sbm_NaniteConstructionSystem, open Config.xml and change `<DebugLogging>0</DebugLogging>` to `<DebugLogging>1</DebugLogging>`
> 2. Load the save in the game and replicate the issue.
> 3. Post NaniteConstructionSystem.log, SpaceEngineers_<date>.log and the save as a reply to this issue.
> 
> Thanks!

Thanks I have solve the issue. I remove the MOD energy shield and put the nanite mod near the top of other. Now no problems. The save problem that I have like other is also fixed :)
My Mod Order:
Uranium and Ice
Text API
Stargate
Nanite
.... other
