### ISSUE TITLE
Nanite and Assembler Not working in Team.

### ISSUE THREAD

**Issue by Midnight-Vortex** [Nanite-Construction-System/NaniteConstructionSystem#82]
@DeveloperofNanite 

I've got a little problem

We connected Nanites and Assembler and use Assembler and Nanite Factory queuing enabled
Nevertheless, the assembler does not work or does not get any components assigned by nanites it should craft.

Something else has to be considered during the construction

**Comment by SplenectomY** [comment]
I can't reproduce. The assembler is not in deconstruct mode? Inventories (including assemblers) are also not immediately recognized due to performance issues. It may take a minute after first building it for it to become part of the NCF's assemblers list.

**Comment by SplenectomY** [comment]
I added a new command: /nanite help assemblers . Let me know if this is still an issue. I still haven't been able to reproduce it reliably, but I'm sure I can refine the code further when I get the chance.

**Comment by tempelon** [comment]
If got the same issue. I tryed severall assemblers not one got an request of the nanites but if i manually craft things the nanites take the items. Do i have to do something else then check the marker by "Nanite Factory Queuing?
