### ISSUE TITLE
Nanite Ore Detector shuts off detecting another recently removed ore detector

### ISSUE THREAD

**Issue by nukeguard** [Nanite-Construction-System/NaniteConstructionSystem#85]
I removed a nanite ore detector and placed a new one a few meters away from original location, and got this message from the new one.  There is only one in the world.
![image](https://user-images.githubusercontent.com/30876973/50719145-09490600-1066-11e9-8204-943c2bfecd71.png)

**Comment by nukeguard** [comment]
did the previous ore detector script not close?

**Comment by nukeguard** [comment]
this is also in offline mode

**Comment by SplenectomY** [comment]
@nukeguard Turn it back on. In your screenshot, it's off.

**Comment by SplenectomY** [comment]
Once an ore detector is removed, it should be fine when you turn it back on.

**Comment by SplenectomY** [comment]
I'll update the text to inform the user to turn the unit back on once the problem has been resolved.

**Comment by nukeguard** [comment]
I had turned it on just prior to that screenshot, was pointing out the warning in the info panel.
