### ISSUE TITLE
Scanning is broken

### ISSUE THREAD

**Issue by Clashsoft** [Nanite-Construction-System/NaniteConstructionSystem#91]
The scanning of the Nanite Factory seems to be broken. Reloading or restarting does not resolve the issue. Please see screenshots attached.

---

![scanning 1](https://user-images.githubusercontent.com/4145923/51087960-45f9b900-175a-11e9-8ffb-82136b03a344.png)
![scanning 2](https://user-images.githubusercontent.com/4145923/51087961-48f4a980-175a-11e9-8e6a-115942bf862d.png)

---

[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2753273/NaniteConstructionSystem.log)

[SpaceEngineers.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2753276/SpaceEngineers.log)

---

![Mod List](https://user-images.githubusercontent.com/4145923/51273830-f3283780-19cd-11e9-82a6-9710c765ad73.png)

![Debug Info](https://user-images.githubusercontent.com/4145923/51088100-f3b99780-175b-11e9-868e-f812c2e4d0d6.png)

**Comment by SplenectomY** [comment]
Thank you for the report. This actually isn't the first time I've experienced this issue with very large block areas (around 50k blocks) for scanning, but I'm having trouble tracking it down, so this may help me. Your mod list image isn't loading for me, and also, _**does this issue happen when no other mods except nanite factory are loaded?**_ Thank you in advance!

**Comment by Clashsoft** [comment]
Yes, without other mods it happens too (but mod list is hopefully fixed now). It also happens with fewer blocks (I tested 1870).

**Comment by Clashsoft** [comment]
I guess the percentage showing either 0.00% or 100.00% is an integer division bug. Something along the lines of `percentDone = (double) (blocksDone / totalBlocks)`, which does integer division rounding down to 0 or 1 if `blocksDone == totalBlocks`.  It should be `percentDone = blocksDone / (double) totalBlocks`. But I couldn't find the relevant code in the repo. Hope this helps.

**Comment by Clashsoft** [comment]
@nukeguard did you fix this? I can't find a related commit

**Comment by Clashsoft** [comment]
@nukeguard the percentage calculation is still not fixed in the latest version of the mod.

**Comment by M0dEx** [comment]
> @nukeguard the percentage calculation is still not fixed in the latest version of the mod.

This was fixed 10 days ago with aea8aa9
