### ISSUE TITLE
(Repair) Beacons turn white after reloading and have wrong description

### ISSUE THREAD

**Issue by Clashsoft** [Nanite-Construction-System/NaniteConstructionSystem#92]
After reloading a world, placed repair beacons (possibly others) turn white. Their description is also incorrect. Please see attached screenshot.

![beacon](https://user-images.githubusercontent.com/4145923/51088122-527f1100-175c-11e9-865c-486ee53fe040.jpg)

---

[NaniteConstructionSystem.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2753273/NaniteConstructionSystem.log)

[SpaceEngineers.log](https://github.com/nukeguard/NaniteConstructionSystem/files/2753276/SpaceEngineers.log)

---
![Mod List](https://user-images.githubusercontent.com/4145923/51273830-f3283780-19cd-11e9-82a6-9710c765ad73.png)

![Debug Info](https://user-images.githubusercontent.com/4145923/51088100-f3b99780-175b-11e9-868e-f812c2e4d0d6.png)

**Comment by SplenectomY** [comment]
Hello @Clashsoft , your modlist image isnt loading for me. Does this problem happen when _**no mods other than nanite factory are loaded**_? Thanks in advance, this just rules out other factors.

**Comment by Clashsoft** [comment]
Mod list image is now hopefully fixed. But I noticed that it also happens without reloading, the beacon just gradually turns white after a while. I don't know if that's a feature.

**Comment by nukeguard** [comment]
The incorrect description is now fixed.

**Comment by Clashsoft** [comment]
@nukeguard What about the beacons turning white?
