### ISSUE TITLE
Reports of nanites deconstructing grids not for deconstruction or separate grids

### ISSUE THREAD

**Issue by nukeguard** [Nanite-Construction-System/NaniteConstructionSystem#98]
@nukeguard I'm not sure if this is a bug. If you de-construct beacon a ship, then attach it to yours with a landing gear thats on the same ship as the factory, after that old ship is cutup the factory will start to take apart the ship its on even if the beacon is gone. Grinding down the facility and rewelding stops this.

This is occuring on a DS

**Comment by nukeguard** [comment]
I'll try this out and see if I can repro

**Comment by kruemelkeksfan** [comment]
I'm playing on a dedicated server and the nanites start disassembling the ship of my friend 200m over. Ships are not connected, no deconstruction beacons at all, "Deconstruction" not even checked neither in the control facility nor the area beacon. Happens with both area beacon active & set to another area and area beacon toggled off. Hacking and rewelding the control station didn't help.

**Comment by Folkloremcgrinme** [comment]
My factories seem to be deconstructing secondary grids. Even near by ships with rotors or pistons with no beacons on them.  The one grid that does have a deconstruct beacon on it they ignore and go for the grid they are attached to instead, again with no beacons or anything with a beacon docked.

**Comment by utoxin** [comment]
I just ran into this issue. If you need a world file that has the issue, I can provide mine.
